FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies for the app if needed
# For a basic app, this may not be required.
# RUN apt-get update && apt-get install -y --no-install-recommends \
#   libpq-dev \
#   && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copy the rest of the application code into the container
COPY . .

# Expose the port Gunicorn will run on
EXPOSE 5000

# Run the Gunicorn server.
# This command starts Gunicorn, which will serve your Flask app.
# The `0.0.0.0` host is important for Docker, allowing it to be accessible from outside the container.
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]

